/**
 * 
 */
package org.bawaweb.euler;

/**
 * @author Navroz
 * https://projecteuler.net/problem=2
 * 
 * 
 * (Sum) Even Fibonacci Numbers
 * -----------------------
 * 
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:	
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence 
 * whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 *
 *
 */
public class EvenFibonacci {

	static int n1 = 0, n2 = 1, n3 = 0;

	static int evenSum = 0;
	static int target = 4000000;
	
	public static void main(String[] args) {
		System.out.println("Sum of the even-valued Fibonacci terms\n whose values\n do not exceed four million\n========================\n");
		doEvenFibonacci();					
		System.out.println(evenSum);

	}
	
	
	static void doEvenFibonacci() {
		while (evenSum < target) {
			n3 = n1 + n2;
			n1 = n2;
			n2 = n3;
			if (n3%2==0) {
				evenSum += n3;
			}
			doEvenFibonacci();
		}
	}
	

}
